export const UPDATE_PROFILE_DETAIL = "UPDATE_PROFILE_DETAIL";
export const UPDATE_SHIP_DETAIL = "UPDATE_SHIP_DETAIL";
export const UPDATE_BILL_DETAIL = "UPDATE_BILL_DETAIL";
export const UPDATE_BILL_MULTIPLE_DETAIL = "UPDATE_BILL_MULTIPLE_DETAIL";
export const UPDATE_SHIPPING_COUNTRY = "UPDATE_SHIPPING_COUNTRY";
export const UPDATE_BILLING_COUNTRY = "UPDATE_BILLING_COUNTRY";
export const UPDATE_SHIPPING_STATE = "UPDATE_SHIPPING_STATE";
export const UPDATE_BILLING_STATE = "UPDATE_BILLING_STATE";
export const UPDATE_ORDER_FORM_DETAIL = "UPDATE_ORDER_FORM_DETAIL";
export const UPDATE_ORDER_FORM_ITEM_DETAIL = "UPDATE_ORDER_FORM_ITEM_DETAIL";
export const UPDATE_ORDER_FORM_ITEM_DETAIL_ADD =
  "UPDATE_ORDER_FORM_ITEM_DETAIL_ADD";
export const UPDATE_ORDER_FORM_ITEM_DETAIL_REMOVE =
  "UPDATE_ORDER_FORM_ITEM_DETAIL_REMOVE";
export const UPDATE_ORDER_FORM_INVOICE_CURRENCY =
  "UPDATE_ORDER_FORM_INVOICE_CURRENCY";
export const UPDATE_ORDER_DIMENSION_FORM = "UPDATE_ORDER_DIMENSION_FORM";
